resolver: lts-12.4

packages:
- libs/api-bot
- libs/api-client
- libs/bilge
- libs/brig-types
- libs/cargohold-types
- libs/cassandra-util
- libs/extended
- libs/galley-types
- libs/gundeck-types
- libs/ssl-util
- libs/metrics-collectd
- libs/metrics-core
- libs/metrics-wai
- libs/ropes
- libs/sodium-crypto-sign
- libs/tasty-cannon
- libs/types-common
- libs/types-common-aws
- libs/types-common-journal
- libs/wai-utilities
- libs/zauth
- services/brig
- services/spar
- services/cannon
- services/cargohold
- services/galley
- services/gundeck
- services/proxy
- tools/bonanza
- tools/makedeb
- tools/api-simulations

- location:
    git: https://github.com/tiago-loureiro/haskell-multihash.git
    commit: 300a6f46384bfca33e545c8bab52ef3717452d12
  extra-dep: true

- location:
    git: https://github.com/wireapp/cryptobox-haskell
    commit: 7546a1a25635ef65183e3d44c1052285e8401608
  extra-dep: true

- location:
    git: https://github.com/kim/hs-collectd
    commit: '0.0.0.2'
  extra-dep: true

- location:
    git: https://github.com/kim/snappy-framing
    commit: d99f702c0086729efd6848dea8a01e5266c3a61c
  extra-dep: true

- location:
    git: https://github.com/tiago-loureiro/aws
    commit: 42695688fc20f80bf89cec845c57403954aab0a2
  extra-dep: true

- location:
    git: https://gitlab.com/twittner/wai-routing
    commit: 7e996a93fec5901767f845a50316b3c18e51a61d
  extra-dep: true

# The version on Haskage (0.9.0.2) deadlocks so here we're using master.
# See https://github.com/jwiegley/async-pool/issues/2
- location:
    git: https://github.com/jwiegley/async-pool
    commit: 5678c13c4ec7d96a55622f7171f8e6a6bb3a3947
  extra-dep: true

# Our fork gives us access to some guts that the upstream 'http-client'
# doesn't expose; see https://github.com/wireapp/wire-server/pull/373
- location:
    git: https://github.com/neongreen/http-client
    commit: 6a4ac55edf5e62574210c77a1468fa7accb81670
  subdirs:
  - http-client
  - http-client-openssl
  - http-client-tls
  - http-conduit
  extra-dep: true

# amazonka-1.6.0 has a bug that's fixed in develop:
# https://github.com/brendanhay/amazonka/issues/466. It's safe to use only
# the 'amazonka' subdir here because other packages weren't changed between
# 1.6.0 and this commit.
- location:
    git: https://github.com/brendanhay/amazonka
    commit: c9d8a62118b2269fb54b1e89c4e92106e8243050
  subdirs:
  - amazonka
  extra-dep: true

# Needs to have QuickCheck bumped: see
# https://github.com/hedgehogqa/haskell-hedgehog/issues/213
- location:
    git: https://github.com/hedgehogqa/haskell-hedgehog
    commit: 7516d04673563455a55cf69eb1c490fbbb7f2a5f
  subdirs:
  - hedgehog-quickcheck
  extra-dep: true

# We want to have at least this commit in:
# https://gitlab.com/twittner/cql-io/commit/94facaca2d9970b91353f947da84634fcd6d78cc
- location:
    git: https://gitlab.com/twittner/cql-io
    commit: 94facaca2d9970b91353f947da84634fcd6d78cc
  extra-dep: true

# Doesn't compile with GHC 8.4; see
# https://gitlab.com/twittner/redis-resp/issues/2
- location:
    git: https://github.com/neongreen/redis-resp
    commit: 86ae383e88dafa4d1a559929e1b75dbba1fd9078
  extra-dep: true

# services/spar:
- location:
    git: https://github.com/wireapp/saml2-web-sso
    commit: 4d6e1af27c81fbaea97e4bcc5c2959c6935d77ec
  extra-dep: true
- location:
    git: https://github.com/wireapp/hsaml2
    commit: 4548e90f34384d10e0186040492b2a652c1cb127
  extra-dep: true
- location:
    git: https://github.com/wireapp/hspec-wai
    commit: ca10d13deab929f1cc3a569abea2e7fbe35fdbe3  # https://github.com/hspec/hspec-wai/pull/49
  extra-dep: true

extra-deps:
- base58-bytestring-0.1.0
- currency-codes-2.0.0.0
- data-timeout-0.3
- geoip2-0.3.1.0
- mime-0.4.0.2
- servant-multipart-0.11.2
- text-icu-translit-0.1.0.7
- wai-middleware-gunzip-0.0.2
- invertible-hxt-0.1  # for hsaml2 / spar

# the following are just not on Stackage (and most of these were present in
# LTS-11 but got evicted in LTS-12)
- bloodhound-0.16.0.0
- template-0.2.0.10
- wai-route-0.4.0
- text-format-0.3.2
- redis-io-0.7.0

flags:
  types-common:
    cql: True
    protobuf: True
    arbitrary: True

extra-package-dbs: []

allow-newer: False
